### ISSUE TITLE
Suggestion: add a screenshot in the README

### ISSUE THREAD

**Issue by rignaneseleo** [simplewidgets/countries_world_map#1]
Hi, this plugin sounds cool but without a screenshot in your README file, it's hard to understand if it fits the use case of a person. 

I suggest you to include some images to make people understand how the map renders and how it looks like.

Thanks

**Comment by LauDijksterhuis** [comment]
Hi @rignaneseleo ,
Thank you for the suggestion, I will add an screenshot and an online example in the near future.
At the moment I am still working on the website for simplewidgets.dev

Untill then you can find a screenshot of the sample app here:
https://simplewidgets.dev/wp-content/uploads/2021/07/countries_world_map.png 

The sample app creates the map and give each country a random color from a list of 5 colors.
Hope you like it

**Comment by rignaneseleo** [comment]
Nice! I pushed a change in the readme so it includes this screenshot. 

Good job, keep it up!

**Comment by LauDijksterhuis** [comment]
Hi @rignaneseleo ,
The website is still under construction, but I uploaded an online example to a subdomain. Please visit: https://pub.dev/packages/countries_world_map to see the changes.

If you have more suggestions let me know!
