### ISSUE TITLE
Adding map pin

### ISSUE THREAD

**Issue by Mohamed50** [simplewidgets/countries_world_map#16]
Hey there. i need some help here. is it possible to add a pin at a specific LatLong point or is there any work around to achieve this?

**Comment by LauDijksterhuis** [comment]
Hello @Mohamed50 ,

Last time I tried I used the original map, but it didn't work.
Last week @cgaisl created a new map: the Mercator world map.

Using this map it should be possible but I havent tried it yet, there are some formulas for calculating this

Please see: https://wiki.openstreetmap.org/wiki/Slippy_map_tilenames 

You can for example add the map in a Stack widget and stack a Positioned Widget / CustomPainter on top that uses the coordinates to display your pin on top of the map.

Keep in mind that you use the exact dimensions as the map you are drawing.

I hope this helps you on your way, I plan to look into this myself in the future

**Comment by EArminjon** [comment]
> Thanks for the information. You gave me an I idea on how to do that. I will let you know if I have achieved that.

Do you achieve something :) ?

**Comment by LauDijksterhuis** [comment]
In the release 1.1.2 and higher there will be a build in function to add Markers to the map based on LAT LONG (special thanks to @EArminjon for the last pull request
