### ISSUE TITLE
example website is down

### ISSUE THREAD

**Issue by EArminjon** [simplewidgets/countries_world_map#18]
[countriesworldmap.simplewidgets.dev](https://countriesworldmap.simplewidgets.dev/)

![image](https://github.com/simplewidgets/countries_world_map/assets/37028599/0e6f2958-d856-4f25-b1e0-aad129715208)

**Comment by LauDijksterhuis** [comment]
Hi @EArminjon 

The link has been replaced to the following: https://examples.simplewidgets.dev/#/countries_world_map 
Thank you for pointing this out, I need to change the README.md to reflect the changes

**Comment by EArminjon** [comment]
INSANE JOB, wp <3

**Comment by LauDijksterhuis** [comment]
The README.md has been updates, thank you!
https://pub.dev/packages/countries_world_map
