### ISSUE TITLE
Feature: Hover Event On Countries and Cities

### ISSUE THREAD

**Issue by NorkQ** [simplewidgets/countries_world_map#23]
Hi,
I want to show some information when users hover on a country/city. How can I implement this?

**Comment by LauDijksterhuis** [comment]
Hi @NorkQ ,

This is similar to issue https://github.com/simplewidgets/countries_world_map/issues/19 and a request I got earlier about displaying flags within the countries. 

For performance we chose to use CustomPainter widget that listens to feedback. 
However, you can use the Stack widget and clip multiple containers (with an Inkwell widget) using the instructions.

I have done this before, if I can find it I will publish the code snippet here.

**Comment by NorkQ** [comment]
Hi @LauDijksterhuis ,
could you find code snippet? It would be perfect for me as a beginner to Flutter.

**Comment by LauDijksterhuis** [comment]
Hi @NorkQ 
Sorry for the delay, I started my own company this year and it has been busy.
Starting today (version 1.2.0) the SimpleMap widget supports this feature out of the box.

Simply add the following line to the widget:
```
onHover: (id, name, isHovering) {
    setState(() {
        if (isHovering) {
            // Do something when hovering (for example change the color)
            colors[id] = Colors.blue;
        } else {
            // Stop doing 
            colors.remove(id);
        }
    });
},
```

Sorry for the wait, I hope this will help your project further 😃

P.S. I love to see what you'll build, so if your project becomes public please let me know.

**Comment by NorkQ** [comment]
Hi again @LauDijksterhuis,
thank you very much and I wish you success in your new business!
I'm developing a volunteering project for an organization. It's not done. But you can see here current version.
[https://luda-project-8244f.web.app](url)

**Comment by LauDijksterhuis** [comment]
Hi @NorkQ 

Thank you for sharing! It looks really cool (even tho I don't understand Russian 😬)
Goodluck with your project, keep me posted if you like!
