### ISSUE TITLE
How to add borders between countries?

### ISSUE THREAD

**Issue by fof-fa** [simplewidgets/countries_world_map#27]
Like this:
![screenshot](https://github.com/simplewidgets/countries_world_map/assets/46462758/d75ad0b9-d2e1-45fb-9bcc-6ec1883ff51d)

**Comment by LauDijksterhuis** [comment]
Hi @fof-fa 

Just add this line to the SimpleMap widget
`  countryBorder: CountryBorder(color: Colors.white, width: 1),`

**Comment by calcitem** [comment]
Hi @LauDijksterhuis,  

First of all, thank you for providing this amazing package, which has been instrumental in my project. I truly appreciate your work!  

However, I am encountering a significant issue regarding country borders that could prevent my application from being published on app stores. Here's the situation:  

### Problem Description  

1. **Risks with Country Borders**  
   Many app stores (e.g., Apple App Store, Google Play Store) have strict policies regarding maps, especially when it comes to representing political boundaries. Certain countries have disputes over territorial borders, and displaying such boundaries (even unintentionally) can lead to compliance issues, rejection during app review, or even legal complications in specific regions.  

2. **Setting `countryBorder` to `null` Still Displays Borders**  
   I attempted to set `countryBorder` to `null`, hoping to completely remove all visual indications of borders. However, fine boundary lines are still visible on the map, which makes it unsuitable for avoiding the risks mentioned above.  

### Suggestions for Improvement  

1. **Option to Completely Remove Borders**  
   It would be incredibly helpful to have an option to render the map without any visual indication of country borders, ensuring a completely boundary-free map for certain use cases. This could be a boolean parameter (e.g., `showBorders: false`) or an enhancement to the existing `countryBorder` implementation to truly hide all borders when set to `null`.  

2. **Support for Imprecise or Generalized Borders**  
   To mitigate risks, another useful feature would be the ability to display simplified or less precise border lines. For example:  
   - Using generalized or smoothed boundary shapes.  
   - Representing regions without implying exact political borders.  
   - Allowing customization of border rendering styles to avoid potential sensitivities (e.g., dashed lines, faint colors).  

These features would provide developers with more flexibility and help avoid risks related to map usage in applications targeting international markets.  

### Questions  

- Is there currently a way to completely hide borders that I might have overlooked?  
- Would you consider implementing the above suggestions or providing guidance on how to achieve these capabilities using this package?  

Thank you for your time and for considering these points. I believe adding such features will greatly enhance the utility and compliance of this package for a wider range of developers.  

Looking forward to your thoughts!
