### ISSUE TITLE
Us States Map Instructions

### ISSUE THREAD

**Issue by wasim353** [simplewidgets/countries_world_map#29]
I have used countries_world_map package for us states map .when i have used the us states map and run the project to see the result is mentions below .
two states are not set right place in map result
1. Alaska
2. Hawaii
![Screenshot_20240806_172719 issue package countries world map](https://github.com/user-attachments/assets/9b58bf79-8bf2-4e3e-9cb7-b227306bb01a)
original map is
![Continent-Maps-Map-of-USA-with-State-Names](https://github.com/user-attachments/assets/a2bac534-1993-4d69-822c-b8a6d28b9ebb)

**Comment by LauDijksterhuis** [comment]
Hi @wasim353 ,

The map that is provided is matched based on how the states are aligning in the real world.
As you can see in the screenshot below the map provided by this packages matches the shapes as displayed on Google Maps.
![usa-map](https://github.com/user-attachments/assets/1e1fdc98-ae75-466e-8865-a3c22417ec89)

Maybe in a future version we will add different versions of the USA map (as we did with the World Map), but for now our goal is to map all countries.
So I will be closing this issue as the map is not wrong.
