### ISSUE TITLE
Coloroung specific countries

### ISSUE THREAD

**Issue by DamianRych** [simplewidgets/countries_world_map#4]
Is it possible to color specific countries with a list or a map?
I can not find anything about that on the internet.
For example
Map countries = {
    "rU" : Colors.accents
  };

SimpleWorldCountryColors(countries );

**Comment by LauDijksterhuis** [comment]
Hi @DamianRych ,

At this moment this is not possible.
Currently the only way is to specify a country color like:

SimpleWorldCountryColors(
rU: Colos.accents,
)

If you would like the feature via Map or List let me know and I will be happy to put it on my to-do list :)

**Comment by LauDijksterhuis** [comment]
I closed this issue since there has been no response for over a few months.

**Comment by GitRubb** [comment]
Is it possible to re open this please. What if you had a list of countries that changes and you had to generate the map programatically, in that case the current implementation would be useless. Something like the above example would work.

**Comment by LauDijksterhuis** [comment]
Hi @GitRubb ,
Sorry for the late response, I was on vacation.

Does the following line meet your needs?
`SimpleWorldCountryColors.fromMap({'ru': Colors.green, ..., ..., ...})`

**Comment by GitRubb** [comment]
Yes that would work, thank you! 
In the meantime I had figured out a workaround which required listing out all countries and having a getColor() function for each one.

**Comment by LauDijksterhuis** [comment]
@GitRubb Thank you for your response

I will try to add this, this weekend. When a newer version is available I will let you know.

Please note:
As described: [in this issue](https://github.com/simplewidgets/countries_world_map/issues/6#issuecomment-1173049761)

I am working on creating a new and better version of this package as well. The way to color the maps will probably stay the same, however it might changes in the future if becomes a limitation for the new package(s)

**Comment by LauDijksterhuis** [comment]
Hello,

I am sorry it has been a while. 
In the latest release (version 1.0.0 and higher) the SimpleMap widget only takes in a Map as input.

There is a helper class named SMap...Colors() which has the .toMap() function added. You can skip it if you like and just provide your own map as long as the id's match.

Also, check out the new maps that have been added (over 130 countries)

**Comment by LauDijksterhuis** [comment]
‼️ Please note

The latest release DOES have breaking changes! And will not work with the old map.
Please read the README.md to get started! Or ask me a question.
