### ISSUE TITLE
Release build

### ISSUE THREAD

**Issue by CoderNamedHendrick** [simplewidgets/countries_world_map#5]
The latest version of this plugin isn't allowing building release apks on android.

This issue persists to even version 0.0.1

**Comment by LauDijksterhuis** [comment]
Hi @CoderNamedHendrick ,

I am aware of this problem (see:  https://github.com/flutter/flutter/issues/94461 )
The painter for the world map is too big for the dart snapshot compiler to process.

I am working on splitting the package (see the issue) and provide higher performance with the new changes.
I hope to release a new version somewhere next week.

Please note: this is not android / grade related. The same problem occurs when building release for iOS.
This does not happen when building release for chrome.

-----

### As a side note: 
I am working on splitting the package in to multiple smaller ones. (For each country one) to prevent downloading too much at once when running pub add countries_world_map.

If you do need all countries that are supported now, there will be an additional package combining all.

**Comment by CoderNamedHendrick** [comment]
Thanks

Waiting for the release 😀😀😀
I would love to contribute too

**Comment by LauDijksterhuis** [comment]
Hi @CoderNamedHendrick 
I will release an update tomorrow which will work for release builds so you can continue your app development.

I am still working on a better performing version. When this will be released I will let you know.
When I have the better performing version ready, I will give you details on how to add any country you like to the project.
But like I said, I will make packages for each country individually. If you have some suggestions or ideas they are much welcome :)

**Comment by LauDijksterhuis** [comment]
@CoderNamedHendrick 
Could you let me know if the newest update works for your app?
Tomorrow I have a day off from school and I will work on the performance issues.

For now I will close this issue, but if the newest version still doesn't work, let me know.

**Comment by CoderNamedHendrick** [comment]
Oh cool, I'll update it and let you know😀

So you're a student? So am I😀😀😀
